SET APP_NAME=CSP554-BDT-B-D-P-P

SET JAVA_HOME=JRE_PATH_IN_YOUR_SYSTEM

SET TWITTER_ACCESS_TOKEN=COPY_FROM_TWITTER_APPLICATION
SET TWITTER_ACCESS_TOKEN_SECRET=COPY_FROM_TWITTER_APPLICATION
SET TWITTER_CONSUMER_KEY=COPY_FROM_TWITTER_APPLICATION
SET TWITTER_CONSUMER_SECRET=COPY_FROM_TWITTER_APPLICATION
SET TWITTER_BEARER_TOKEN=COPY_FROM_TWITTER_APPLICATION
SET TWITTER_FILTER_KEYWORD_LIST=python,big data

SET ZOOKEEPER_HOST_NAME=localhost
SET ZOOKEEPER_PORT=2181

SET KAFKA_HOST_NAME=localhost
SET KAFKA_PORT=9092
SET KAFKA_TOPIC_NAME=BIG_DATA

SET SPARK_HOME=%cd%\server\spark-2.4.7-bin-hadoop2.7
SET HADOOP_HOME=%cd%\server\hadoop-2.7

SET NODE_JS_WEB_SERVER_PORT=3000

SET DATA_DIR_LOCAL_PATH=%cd%\data
SET SPARK_DATA_DIR_LOCAL_PATH=%DATA_DIR_LOCAL_PATH%\spark\json_tweet

SET GOOGLE_APPLICATION_CREDENTIALS=%cd%\server\firebase\service-account\admin-sdk\ADMIN_SDK_FILE_NAME
SET FIREBASE_REALTIME_DATABASE_URL=COPY_URL_FROM_FIREBASE_CONSOLE
SET SPARK_DATA_FIREBASE_REALTIME_DATABASE_PATH=/spark/json_tweet

SET PATH=%HADOOP_HOME%\bin;%JAVA_HOME%\bin;%PATH%